name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    name: "Pytest"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Pyright
        run: |
          uv run pyright

      - name: Pytest
        run: |
          uv run coverage run -m pytest
          uv run coverage combine -q
          uv run coverage report -m
        env:
            PYTEST_ADDOPTS: "--color=yes"
            FORCE_COLOR: "3"
