name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    name: "Pytest"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          version: "0.11.6"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Ruff
        run: |
          uvx ruff check
          uvx ruff format --check

      - name: Pyright
        run: |
          uv run pyright

      - name: Pytest
        run: |
          uv run coverage run -m pytest
          uv run coverage combine -q
          uv run coverage report -m
        env:
            PYTEST_ADDOPTS: "--color=yes"
            FORCE_COLOR: "3"
